// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAvPJdX9m1gGQuv-Q81DU6_bfIPi1gItc',
    appId: '1:1075727396738:web:49b324a8fe6b577487e99b',
    messagingSenderId: '1075727396738',
    projectId: 'skinvisionai-2026',
    authDomain: 'skinvisionai-2026.firebaseapp.com',
    storageBucket: 'skinvisionai-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_MGKhHFX4IweyAOyHTH6LWTKw3boI2I',
    appId: '1:1075727396738:android:02714d0f9524f73387e99b',
    messagingSenderId: '1075727396738',
    projectId: 'skinvisionai-2026',
    storageBucket: 'skinvisionai-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAjVyQ9ODRxjYWVluEI7V8uJvbC6bz9E',
    appId: '1:1075727396738:ios:7d971f576d15acab87e99b',
    messagingSenderId: '1075727396738',
    projectId: 'skinvisionai-2026',
    storageBucket: 'skinvisionai-2026.firebasestorage.app',
    iosClientId: '1075727396738-olmpi4tei6t85rvrlqnnqki1lie5trau.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAjVyQ9ODRxjYWVluEI7V8uJvbC6bz9E',
    appId: '1:1075727396738:ios:7d971f576d15acab87e99b',
    messagingSenderId: '1075727396738',
    projectId: 'skinvisionai-2026',
    storageBucket: 'skinvisionai-2026.firebasestorage.app',
    iosClientId: '1075727396738-olmpi4tei6t85rvrlqnnqki1lie5trau.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinDetectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAvPJdX9m1gGQuv-Q81DU6_bfIPi1gItc',
    appId: '1:1075727396738:web:e55c58a507b6ff0287e99b',
    messagingSenderId: '1075727396738',
    projectId: 'skinvisionai-2026',
    authDomain: 'skinvisionai-2026.firebaseapp.com',
    storageBucket: 'skinvisionai-2026.firebasestorage.app',
  );
}
